name: Build Mac - Apple Silicon and Intel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-13]
        arch: [amd64, arm64]
        exclude:
          - os: macos-latest
            arch: arm64
          - os: macos-13
            arch: amd64     
    env:
      BUILD_MAC: true
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Env
      run: env
      
    - name: test
      run: make test
      
    - name: Build
      run: make

    - name: End-to-end test
      run: make e2e

    - name: Copy for packaging
      run: |
        cp bin/* .
        cp cmd/service/com.example.everythingxd.plist .

    - name: Upload package
      if: ${{ env.BUILD_MAC == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: everythingx.${{ runner.os }}-${{ runner.arch }}
        path: |
          everythingx
          ev
          everythingxd
          install.sh 
          uninstall.sh 
          com.example.everythingxd.plist 
        if-no-files-found: error

